config/routes.rb
Rails.application.routes.draw do
 
  resources :posts
  #get 'messages/inbox' 

  resources :messages do
    collection do
      get :inbox
      get :sent
    end
  end   
  
  

  post 'toggle_like' => 'likes#toggle' 
  post 'coment' => 'post#coment'

  get 'profile' => 'users#edit'
  put 'update'  => 'users#update'
  get 'friends' => 'friends#index'

  #get 'auth/provider/callback' => 'sessions#callback'

  delete 'remove_friend' => 'friendships#destroy'
  resources :friendships

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  resources :users

  
  get 'users/new'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


  
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user 
  belongs_to :friend, class_name: "User"
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true

  #before_action :authenticate_user! # devise method to help ensure logging in
   
  

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name:"User"
  belongs_to :recipient, class_name:"User"

end

app/models/post.rb
class Post < ApplicationRecord

  validates :body, presence: true
  belongs_to :wall_user, class_name:"User"
  belongs_to :poster, class_name:"User"
  has_many :likes, as: :item
  has_many :coments

  

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :sent_messages, class_name:"Message", foreign_key:"sender_id"
  has_many :recipient_messages, class_name:"Message", foreign_key:"recipient_id" 

  mount_uploader :avatar, AvatarUploader

  has_many :posts, foreign_key: "poster_id", dependent: :destroy
  has_many :posts_on_his_wall, class_name: 'Post', foreign_key: 'wall_user_id'
  has_many :likes, dependent: :destroy
 
  has_secure_password

  # def password=(value)
  #   @password = value
  #   self.password_digest = BCrypt::Password.create(value)
  #   end

  # def password
  #   @password
  # end

  # def is_valid?(current_password)
  #   BCrypt::Password.new(current_password) == password_digest
  # end

  #---------------------------------------------------------

  #def self.from_omniauth(auth)

  # email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
  # user = where(email: eamil).first_or_initialize
  # user.image_url = auth[:info][:image]
  # user.name = auth[:info][:name]
  # user.password = SecureRandom.hex
  #user.save && user
  #end

#-----------------------------------------------------------

#  def friends
#   result = []
#   friendships.each do |f|
#     result << f.friend
#   end
#   result
#  end
#------------------------------------------------------------

  def image_default
    avatar.url || image_url.presence || "http://lorempixel.com/128/128/sports/fake-user/"
  end 

  def add_friend(another)
    friends << another
  end

  def is_friend?(another_user)
    friends.include?(another_user)
  end

  def friend_names
    friends.map{|e| e.name}
  end

  def self.except(user)
    all - [user]
  end

  def self.recipient_options(user)
    except(user).map{|e| [e.name, e.id]}
  end  

   def self.generate_users(u)
     url = "https://randomuser.me/api?gender=female&results=#{u}"
     response = HTTP.get(url)
     data = response.parse
     people = data["results"]
     people.each do |p|
       name = p["name"]["first"] + " "+p["name"]["last"]
       User.create!(
        name: name.titleize, password: p["login"]["password"],
        email: p["email"], image_url: p["picture"]["large"]
       ) 
     end  
   end  


  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
   end  
  end
 
  def name_or_email
    name.present? ? name : email
  end 

  def liking?(item)
    likes.where(item: item).exists?
  end


 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user 
  helper_method :friend_user 
  

  private 

  def require_login
    unless current_user
      redirect_to root_path, flash: {error: "Access Denied.."}
    end
  end

  def log_in(user)
    session[:user_id] = @user.id
  end

  def log_out(user)
    session[:user_id] = nil
  end

  def current_user
    return @current_user if @current_user

    if session[:user_id]
      @current_user = User.find(session[:user_id])
     else
      nil 
    end
  end

  
  def current_message

  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    #friendship_params[:user_id] == current_user.id 
    current_user.friendships.create!(friendship_params)
    redirect_to users_path
  end

  def destroy
    another_user = User.find params[:user_id]
    current_user.friends.delete(another_user)
    redirect_to users_path
  end

  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @post = Post.new
    @posts = current_user.posts + current_user.posts_on_his_wall if current_user
  end



end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  #before_action :authenticate_user! # devise method to help ensure logging in
   
  def toggle
    if params[:post_id]
      @item = Post.find params[:post_id]
    end
    
    current_user.toggle_like!(@item)

    respond_to do |format|
      format.html {redirect_back fallback_location: root_path}
      format.js
     end

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    redirect_to inbox_messages_path
  end 

  def inbox
    @messages = current_user.recipient_messages
  end

  def sent
    @messages = current_user.sent_messages
  end  

  def new
    @message = Message.new
  end
  
  def create
    @message = current_user.sent_messages.build message_params
    if @message.save
      redirect_to sent_messages_path
      else
    
     render "new"
    end 
  end 

  private

  def message_params
    params.require(:message).permit(:recipient_id, :body)
  end
  
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #before_action :require_login

  def new
    @post = Post.new
  end  

  def create
    @post = current_user.posts.build post_params
  
     if @post.save
       #flash[:success] = 'Post created'
       redirect_to root_path
     else
       #flash[:error] = @post.errors.full_messages.to_sentence
       render 'new'
     end
    
  end 
  
  def post_params
    params.require(:post).permit(:body, :poster_id, :wall_user_id)
  end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
   if @user = User.find_by(email: params[:email])
      if @user.authenticate(params[:password])
          log_in(@user)
          redirect_to root_path, flash:{notice: "login.."}
        else
          redirect_to login_path, flash:{notice: "Invalid password"}  
      end  
    else
     redirect_to login_path, flash:{notice: "Invalid Email"}    
    end
    #redirect_to root_path
  end

  def destroy
    log_out(current_user)
    redirect_to root_path
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in(@user)
      redirect_to root_path
      flash[:success] = "User saved ¡!"
     else
      render "new"
    end
  end  

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = User.create user_params
    redirect_to root_path
  end 

 private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/toggle.js.erb
$("#<%= dom_id @item%>").find(".js-like-button").toggleClass("is-liked");

app/views/messages/_message.html.erb
<article class="message">
    <div class="message-header">
      <div>
        <strong>From :</strong><%= message.sender.name.titleize %>
      </div>
      <div>
        <strong>To :</strong><%= message.recipient.name.titleize %>
      </div>
        <button class="delete" aria-label="delete"></button>
    </div>

    <div class="message-body">
      <strong>Message</strong>
      <p><%= message.body %></p>
    </div>
  </article>

app/views/messages/inbox.html.erb
<h1 class="title">Inbox</h1>

<% @messages.each do |message|%>
  <%= render message %>
<% end %>

app/views/messages/new.html.erb
<h1 class="title">Compose Message</h1>

<%= form_for @message do |f|%>
  <div class="field">
    <div class="control">
      <%= f.label :recipient_id, class:"label"  %>
      <div class="select">
        <%= f.select :recipient_id, User.recipient_options(current_user) %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.label :body, class:"label"  %>
      <%= f.text_area :body , class:"textarea" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <button class="button is-success">Send</button>
    </div>
  </div>
<% end %>

app/views/messages/sent.html.erb
<h1 class="title">Sent</h1>

<%= render @messages %>

app/views/posts/_post.html.erb
<div class="post card" id="<%= dom_id post %>">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <img src="https://coderschool123.s3-ap-southeast-1.amazonaws.com/uploads/twitter-square.jpeg" alt="">
          </p>
        </div>
        <div class="media-content">
          <p class="is-title">
            <strong><%= link_to post.poster.email, "/" %></strong>
          </p>
          <small><%= time_ago_in_words post.updated_at %> ago</small>
        </div>
      </div>
      <div class="content">
        <%= simple_format post.body %>
      </div>
    </div>
    <div class="card-footer">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <%= link_to fa_icon("thumbs-up", text: "Like"), toggle_like_path(post_id: post.id), class: "js-like-button button is-white #{'is-liked' if current_user.liking?(post)}", method: "post", remote: true %>

             <%= post.likes.map {|e| e.user.email }.to_sentence %>
          </div>
          <div class="level-item">
            <%= link_to fa_icon("comments", text: "Comment"), "/", class: "button is-white" %> 
            
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<h1 class="title"> Write Something</h1>

<%= form_for @post do |f| %>
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      <p> To : </p>
      <%= f.text_field :wall_user_id %>
      <%= f.hidden_field :poster_id %>
    </p>
  </header>
  
  <div class="card-content">
    <div class="content">
      <%= f.text_area :body, class:"textarea" %>
    </div>
  </div>
  <footer class="card-footer">
    <a class="card-footer-item"><%= f.submit class:"card-footer-item button is-primary is-outlined", value:"Send" %></a>
  </footer>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter card">
    <%= form_for user do |f| %>
      <div class="field">
        <label class="label">Name</label>
        <div class="control">
          <%= f.text_field :name , class:"input control", placeholder:"name"%>
        </div>
      </div>

      <div class="field">
        <label class="label">Email</label>
        <div class="control">
          <%= f.text_field :email , class:"input control", placeholder:"email"%>
        </div>
      </div>
        
      <div class="field">
        <label class="label">Password</label>
        <div class="control">
          <%= f.password_field :password , class:"input control", placeholder:"password"%>
        </div>
      </div>

      <div class="field">
        <label class="label">Pasword Confirmation</label>
        <div class="control">
          <%= f.password_field :password_confirmation , class:"input control", placeholder:"confirmation password"%>
        </div>
      </div>

      <div class="field">
        <%= f.label :avatar, class:"label"%>
        <div class="control"><%= f.file_field :avatar, class: 'input' %>
        </div>
      </div>
          
      <div class="field is-grouped">
          <div class="control">
            <%= f.submit 'Create account' , class:"button is-primary" %>
          </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="content"><h1 class="title "><%= current_user.name.titleize %>'s profile </h1></div>
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="card user-card">
      <div class="card-content">
        <%= form_for @user do |f| %>
          <div class="field">
            <div class="label">Name</div>
            <div class="control">
              <%= f.text_field :name, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Email</div>
            <div class="control">
              <%= f.text_field :email, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Password</div>
            <div class="control">
              <%= f.password_field :password, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <%= f.label :avatar, class:"label"%>
            <div class="control">
            <%= f.file_field :avatar, class: 'input' %>
            </div>
          </div>
          
          <div class="field">
            <div class="control">
              <%= image_tag current_user.image_default %>
            </div>
          </div>
          
          <%= f.submit "Update Profile", class: "button is-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<table class="table">
  <tbody>
    <% User.all.each do |another_user| %>
      <tr>
        <td><%= image_tag another_user.image_default %></td>
          <td>
            <%= another_user.name %></br>
            <%= another_user.email %>
          </td>  
           <td>
            <% if current_user.is_friend?(another_user) %>
                <%= link_to "Remove Friend", remove_friend_path(user_id: another_user.id), class:"button is-danger is-outlined", method: :delete %>
              <%  else %>
              <%= form_for current_user.friendships.build(friend: another_user)  do |f|%>
                <%= f.hidden_field :friend_id%>
                <button class="button is-success">Add Friend</button>
                <% end %>
            <% end %>    
          </td>
      </tr>
    <% end %>
  </tbody>
</table>    

app/views/users/new.html.erb
<h1 class="title"> Join us </h1>
  <%= render  "form" , user: @user  %>

app/views/users/show.html.erb
<% if current_user.friends %>
    <div class="columns ">
      <div class="card column is-3">
        <h1 class="title">Hello <%= current_user.friends.name.titleize %> </h1>
      
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= image_tag current_user.friends.image_default %>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"></p>
            <p class="subtitle is-6"><%= current_user.friends.email%></p>
          </div> 
        </div>
      </div>
      
      <div class="card column is-5">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                
              </figure>
            </div>
            <div class="media-content">
            <%= render file:"posts/new" %>
            </div>
          </div>

          <div class="content">
           <h3 class="title">Posts</h3>
              <%= render current_user.friends.posts_on_his_wall %>
            <br>
          </div>
        </div>
      </div>  

      <div class="box">
        <% User.all.each do |another_user| %>
          <% if current_user.is_friend?(another_user) %>
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <%= image_tag another_user.another_image %>
                </figure>
              </div>
              <div class="media-content">
                  <div class="content">
                    <p>
                      <strong><%= another_user.name %></strong> <small><%= another_user.email %></small> 
                      <br>
                      Lorem ipsum dolor sit amet, consectetur</br>sit amet massa fringilla egestas. Nullam condimentum luctus turpis.
                    </p>
                  </div>
              </div>
            </article>
             <% end %>
          <% end %>   
        </div>

      </div>

  <% end %>